### ISSUE TITLE
中文空格规定更新

### ISSUE THREAD

**Issue by AnzhiZhang** [CFPAOrg/TransRules#1]
该规定会造成误导
![image](https://user-images.githubusercontent.com/37402126/167253608-092c8256-1482-4268-87ec-2c97a03e93cd.png)
![167253402-5e9b07f6-0f6a-4e8e-b566-6e19b12fc0fb](https://user-images.githubusercontent.com/37402126/167253589-2028280b-583e-4d87-8856-3b8e016036e7.png)

**Comment by AnzhiZhang** [comment]
参考 [CFPAOrg/Minecraft-Mod-Language-Package#1961](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1961#pullrequestreview-965325360)

**Comment by n0099** [comment]
建议消歧义

**Comment by AnzhiZhang** [comment]
建议，在这部分任务加上仅适用1.12
